#!/usr/bin/env python3
"""
Vendors the Google Fonts the app actually uses into `apps/web/public/fonts`,
and regenerates `apps/web/src/fonts.css` to point at them.

Kintara runs on a NAS that is frequently offline or firewalled, so nothing may
be fetched from a CDN at runtime. Run this when the font list in Settings
changes; commit both the woff2 files and the regenerated CSS.

    python3 scripts/vendor-fonts.py
"""
import re
import subprocess
import pathlib

# Pretending to be a browser is what gets woff2 back. With curl's own
# User-Agent, Google serves ttf, which is roughly twice the size.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

# The app renders 400, 500, 600 and 700 and nothing else, so that is the whole
# range worth shipping. Variable families are requested as a range: Google
# serves one file covering all of it, where enumerating the weights returns the
# same file four times under four `font-weight` declarations.
VARIABLE = [
    ("Inter", "Inter"),
    ("Outfit", "Outfit"),
    ("M+PLUS+U", "M PLUS U"),
]

# Static families, where each weight is a genuinely different file. Only the
# weights each one actually publishes -- Bellota has no 500 or 600, and Elsie
# is only drawn at 400 and 900.
STATIC = [
    ("Livvic", "Livvic", [400, 500, 600, 700]),
    ("Bellota", "Bellota", [400, 700]),
    ("Elsie", "Elsie", [400, 900]),
]

# The interface is English. The other subsets Google offers -- cyrillic, greek,
# vietnamese -- would roughly double the payload for glyphs nothing renders.
KEEP_SUBSETS = ("latin", "latin-ext")

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "apps/web/public/fonts"
CSS_PATH = ROOT / "apps/web/src/fonts.css"

HEADER = """/*
 * Self-hosted webfonts. Generated by `scripts/vendor-fonts.py` -- edit that
 * rather than this file.
 *
 * Nothing may be fetched at runtime: Kintara is built to run on a NAS that is
 * frequently offline or firewalled, and a CDN font is the one dependency that
 * degrades silently rather than visibly.
 *
 * Only the latin and latin-ext subsets are shipped, and only the weights the
 * app renders. Italic faces are deliberately absent -- `.italic` appears twice
 * in the whole interface, and a synthesised oblique is the better trade
 * against doubling the number of files.
 */

"""


def fetch(url: str) -> bytes:
    return subprocess.run(
        ["curl", "-sS", "--fail", "-m", "60", "-A", UA, url],
        check=True, capture_output=True).stdout


def faces(css: str):
    """Yields (subset, block) for each @font-face, which Google labels with a
    preceding /* subset */ comment."""
    for subset, block in re.findall(
            r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css):
        if subset in KEEP_SUBSETS:
            yield subset, block


def slug(family: str) -> str:
    return family.lower().replace(" ", "-").replace("+", "-")


def vendor(query: str, family: str):
    """Downloads one css2 response's faces and rewrites them to local paths.

    One request covers every weight of a family, so the file name is taken from
    each face's own `font-weight` -- a single number for a static face, or the
    `400 700` range a variable one declares.
    """
    css = fetch(
        f"https://fonts.googleapis.com/css2?family={query}&display=swap").decode()
    out = []
    for subset, block in faces(css):
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        weight = re.search(r"font-weight:\s*([\d ]+);", block).group(1).strip()
        name = f"{slug(family)}-{weight.replace(' ', '-')}-{subset}.woff2"
        data = fetch(url)
        (OUT_DIR / name).write_bytes(data)
        print(f"  {name:<40} {len(data) / 1024:>7.1f} KB")
        out.append(block.replace(url, f"/fonts/{name}"))
    return out


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in OUT_DIR.glob("*.woff2"):
        stale.unlink()

    blocks = []
    for query, family in VARIABLE:
        blocks += vendor(f"{query}:wght@400..700", family)
    for query, family, weights in STATIC:
        joined = ";".join(str(w) for w in weights)
        blocks += vendor(f"{query}:wght@{joined}", family)

    CSS_PATH.write_text(HEADER + "\n\n".join(blocks) + "\n")
    total = sum(f.stat().st_size for f in OUT_DIR.glob("*.woff2"))
    print(f"\n{len(blocks)} faces, {total / 1024:.0f} KB in {OUT_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
